---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: email notification on start
    image: mashirozx/drone-email:latest-arm64
    failure: ignore
    settings:
      host: 
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_username
      password:
        from_secret: smtp_password
      from.address:
        from_secret: smtp_from_address
      from.name:
        from_secret: smtp_from_name
      recipients:
        from_secret: smtp_recipients
      subject: >
        {{repo.owner}}/{{repo.name}}:${DRONE_COMMIT_BRANCH} arm64 build #${DRONE_BUILD_NUMBER} start
      body: >
        ${DRONE_COMMIT_MESSAGE}<br /><br />
        Git repo: {{repo.owner}}/{{repo.name}}<br />
        Git branch: ${DRONE_COMMIT_BRANCH}<br />
        Git hash: <a href="${DRONE_COMMIT_LINK}" target="_blank">${DRONE_COMMIT_SHA}</a><br />
        Git author: ${DRONE_COMMIT_AUTHOR_NAME} (${DRONE_COMMIT_AUTHOR})<br />
        <br />View CI detail: {{build.link}}
        <br /><br />
        Drone CI ${DRONE_SYSTEM_VERSION}
    when:
      branch:
        - main
      event:
        - push
        - tag

  - name: build arm64 image
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      tags: 
        - latest-arm64
        - sha-${DRONE_COMMIT_SHA:0:8}-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.slim
      squash: true
    when:
      branch:
        - main
      event:
        - push

  - name: email notification on complete
    image: mashirozx/drone-email:latest-arm64
    failure: ignore
    settings:
      host: 
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_username
      password:
        from_secret: smtp_password
      from.address:
        from_secret: smtp_from_address
      from.name:
        from_secret: smtp_from_name
      recipients:
        from_secret: smtp_recipients
      subject: >
        {{#success build.status}}
          {{repo.owner}}/{{repo.name}}:${DRONE_COMMIT_BRANCH} arm64 build #${DRONE_BUILD_NUMBER} succeeded
        {{else}}
          {{repo.owner}}/{{repo.name}}:${DRONE_COMMIT_BRANCH} arm64 build #${DRONE_BUILD_NUMBER} failed
        {{/success}}
      body: >
        ${DRONE_COMMIT_MESSAGE}<br /><br />
        Git repo: {{repo.owner}}/{{repo.name}}<br />
        Git branch: ${DRONE_COMMIT_BRANCH}<br />
        Git hash: <a href="${DRONE_COMMIT_LINK}" target="_blank">${DRONE_COMMIT_SHA}</a><br />
        Git author: ${DRONE_COMMIT_AUTHOR_NAME} (${DRONE_COMMIT_AUTHOR})<br />
        <br />View CI detail: {{build.link}}
        <br /><br />
        Drone CI ${DRONE_SYSTEM_VERSION}
    when:
      branch:
        - main
      event:
        - push
        - tag
      status:
        - success
        - failure
